fos_rest:
    body_listener: true
    param_fetcher_listener: true
    routing_loader:
        default_format:  json
        include_format:  false
    format_listener:
        rules:
        - { path: ^/api, priorities: ['json', 'html', '*/*'], fallback_format: json, prefer_extension: true }
        - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
    zone:
        - { path: ^/api/* }
