sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~

    audit:
        force: true

    templates:
        form:
            - "@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig"