twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'
    date:
        format: d/m/Y H:i
        interval_format: '%%d days'
    form_themes:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - '@SonataMedia/Form/media_widgets.html.twig'
            - '@SonataCore/Form/color.html.twig'